(ns euler-clj.core
  (:require [clojure.math.numeric-tower :as m])
  (:gen-class))

;; 1
;;
;; Project Euler
;; If we list all the natural numbers below 10 that are multiples of 3 or 5,
;; we get 3, 5, 6 and 9. The sum of these multiples is 23.
;; Find the sum of all the multiples of 3 or 5 below 1000.
;; Right answer is 233168
(defn problem-1
  []
  (reduce #(if (or (= (mod %2 3) 0) (= (mod %2 5) 0)) (+ %1 %2) %1) 0 (range 1 1000)))
(println (str "Problem 1: " (problem-1)))

;; 2
;;
;; Project Euler
;; Each new term in the Fibonacci sequence is generated by adding the previous
;; two terms. By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not
;; exceed four million, find the sum of the even-valued terms.
;; Right answer is 4613732
(defn problem-2
  []
  (let [limit 4000000]
    (loop [term 1
           sum (+ term term)
           even-nums 0]
      (if (< sum limit)
        (recur sum (+ term sum) (if (even? sum) (+ even-nums sum) even-nums))
        even-nums))))
(println (str "Problem 2: " (problem-2)))

;; 3
;;
;; The prime factors of 13195 are 5, 7, 13 and 29.
;; What is the largest prime factor of the number 600851475143?



;; 6
;;
;; The sum of the squares of the first ten natural numbers is,
;; 1^2 + 2^2 + ... + 10^2 = 385
;;
;; The square of the sum of the first ten natural numbers is,
;; (1 + 2 + ... + 10)^2 = 55^2 = 3025
;;
;; Hence the difference between the sum of the squares of the first ten natural
;; numbers and the square of the sum is 3025 − 385 = 2640.
;:
;; Find the difference between the sum of the squares of the first one hundred
;; natural numbers and the square of the sum.

(defn problem-6
  []
  (let [nums (take 101 (range))]
    (- (m/expt (reduce #(+ %1 %2) 0 nums) 2)
       (reduce + 0 (map #(m/expt % 2) nums)))))
(println (str "Problem 6: " (problem-6)))
